### ISSUE TITLE
Vagrant up fails ... Could not resolve host: cloud-images.ubuntu.com

### ISSUE THREAD

**Issue by RandoSY** [carlosperate/microbit-dev-env#3]
Bringing machine 'microbit-vg' up with 'virtualbox' provider...
==> microbit-vg: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    microbit-vg: Box Provider: virtualbox
    microbit-vg: Box Version: >= 0
==> microbit-vg: Loading metadata for box 'ubuntu/trusty64'
    microbit-vg: URL: https://vagrantcloud.com/ubuntu/trusty64
==> microbit-vg: Adding box 'ubuntu/trusty64' (v20170818.0.0) for provider: virtualbox
    microbit-vg: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20170818.0.0/providers/virtualbox.box
    microbit-vg: Progress: 0% (Rate: 0curl:/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Could not resolve host: cloud-images.ubuntu.com

**Comment by carlosperate** [comment]
The image is hosted by Ubuntu, so I don't have any control over it. Are you sure you had a working internet connection when trying to "vagrant up"?

**Comment by RandoSY** [comment]
Thanks for the consideration of your prompt reply. This situation resolved the next day, so it was some sort of server side interruption.  So, I guess, patience is key.  This is a very valuable tool, thanks for all your hard work!

**Comment by carlosperate** [comment]
No problem, glad you got it working!
I'll close this issue, but feel free to open any other if you have any questions.
